---
version: "3.8"

services:

 # ADL stands for Ansible - Docker - Linux
  adl:
    image: neomn110/adl
    container_name: adl
    restart: unless-stopped
    tty: true
    volumes:
      - type: bind
        source: inventories/main_inventory
        target: /ansible/inventory
      - type: bind
        source: inventories/setup_ssh_inventory
        target: /ansible/roles/setup_ssh_connection/inventory
      - type: bind
        source: ./.secrets/application_nodes.yml
        target: /ansible/group_vars/application_nodes.yml
      - type: bind
        source: .secrets
        target: /secrets
