- hosts: application_nodes
  become: yes
  become_user: root
  # roles:
    # - install_docker 
  
  tasks:
    - name: use a mirror registry for docker
      debug:
        msg: ''

    - name: change docker default ip address
      debug:
        msg: ''

    - name: change docker logging format
      debug:
        msg: ''

    - name: run nginx and nexus container
      debug:
        msg: ''

    - apply nexus configs
      debug:
        msg: ''
