

---
version: "3.8"
 
networks:
  gateway:
    external: true
  app:
    external: true
  db: 
    external: true

volumes:
  gateway:
    driver: local
  mysql:
    driver: local
  wordpress-nginx:
    driver: local


services:

  gateway:
    image: neomn110/main:nephews5.app-gateway.0.0.1
    container_name: gateway
    hostname: gateway
    restart: always
    tty: true
    volumes:
        - gateway:/var/log/nginx
    ports:
        - 80:80
        - 443:443
    networks:
        - gateway

  wordpress-server:
    image: neomn110/main:nephews5.wordpress-server.0.0.1
    container_name: wordpress-server
    hostname: wordpress-server
    restart: always
    tty: true
    volumes:
      - wordpress-nginx:/var/www/html
    depends_on:
      - wordpress
      - mysql
    networks:
      - gateway
      - app

  wordpress: 
    image: neomn110/main:nephews5.wordpress.0.0.1
    container_name: wordpress
    hostname: wordpress
    restart: always
    tty: true
    volumes:
      - wordpress-nginx:/var/www/html
    depends_on: 
      - mysql
    networks:
      - app
      - db
    environment:
      WORDPRESS_DB_HOST     : ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER     : ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD : ${WORDPRESS_DB_PASSWORD} 
      WORDPRESS_DB_NAME     : ${WORDPRESS_DB_NAME}

  mysql:
    image: mysql:5.6.51
    container_name: mysql
    hostname: mysql
    restart: always
    tty: true
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}    
      MYSQL_USER:          ${MYSQL_USER}         
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}

