---
#==========   apply docker custom configurations   ================
- name: copy daemon.json to server at path /etc/docker
  copy: 
    src: ../files/daemon.json
    dest: /etc/docker/
    owner: root
    group: root
    mode: 0644
  notify: restart_docker
